/**
 * @l2/contracts — API pública.
 *
 * §9.3: lo que no se exporta aquí no es importable desde fuera. Un contrato
 * que no está en esta lista todavía no es un contrato, es un borrador.
 */

export {
  IdSchema,
  TimestampSchema,
  FechaSchema,
  CurrencySchema,
  MoneySchema,
  IdempotencyKeySchema,
  ApiErrorSchema,
  POR_PAGINA,
  PaginaSchema,
  PorPaginaSchema,
  type PorPagina,
  type Id,
  type Timestamp,
  type Fecha,
  type Currency,
  type MoneyDto,
  type IdempotencyKey,
  type ApiError,
} from "./primitives.ts";

export {
  WristbandCodeSchema,
  GuardianSchema,
  KidSchema,
  DurationSchema,
  SessionModeSchema,
  PricePackageSchema,
  ParkPolicySchema,
  TarifarioSchema,
  SessionStatusSchema,
  ParkSessionSchema,
  ParkTermsSchema,
  EstanciaSchema,
  BuscarRepresentanteSchema,
  ConsultarPulseraSchema,
  EstadoPulseraSchema,
  type EstadoPulseraDto,
  RepresentanteEncontradoSchema,
  RecargaCommandSchema,
  PausaCommandSchema,
  PausaSchema,
  type PausaCommand,
  type PausaDto,
  RecargaResultSchema,
  CierreHuerfanaCommandSchema,
  AnularEntradaCommandSchema,
  type AnularEntradaCommand,
  type RecargaCommand,
  type RecargaResult,
  type CierreHuerfanaCommand,
  MonitorSnapshotSchema,
  CheckInCommandSchema,
  CheckInResultSchema,
  RepresentanteSchema,
  DirectorioRepresentantesSchema,
  RepresentanteCommandSchema,
  NombrarEstanciaCommandSchema,
  type WristbandCode,
  type GuardianDto,
  type KidDto,
  type DurationDto,
  type SessionMode,
  type PricePackageDto,
  type ParkPolicyDto,
  type TarifarioDto,
  TarifarioPublicadoSchema,
  PaginaDeVersionesTarifarioSchema,
  VersionTarifarioSchema,
  VersionesTarifarioQuerySchema,
  type PaginaDeVersionesTarifarioDto,
  type VersionTarifarioDto,
  type VersionesTarifarioQuery,
  type TarifarioPublicadoDto,
  type SessionStatus,
  type ParkSessionDto,
  type ParkTermsDto,
  type EstanciaDto,
  type RepresentanteEncontradoDto,
  type MonitorSnapshotDto,
  type CheckInCommand,
  type RepresentanteDto,
  type DirectorioRepresentantesDto,
  type RepresentanteCommand,
  type NombrarEstanciaCommand,
  type CheckInResult,
} from "./park.ts";

export {
  RatePairSchema,
  RateSourceSchema,
  RateValueSchema,
  HeldReasonSchema,
  AlertaTasaSchema,
  ExchangeRateSchema,
  HistorialTasasSchema,
  FiltroTasasSchema,
  PaginaDeTasasSchema,
  TasasQuerySchema,
  type FiltroTasas,
  type PaginaDeTasasDto,
  type TasasQuery,
  CapturarTasaCommandSchema,
  ConfirmarTasaCommandSchema,
  SincronizacionTasaSchema,
  type RatePair,
  type RateSource,
  type HeldReason,
  type AlertaTasaDto,
  type ExchangeRateDto,
  type HistorialTasasDto,
  type CapturarTasaCommand,
  type ConfirmarTasaCommand,
  type SincronizacionTasaDto,
} from "./tasas.ts";

export {
  CodigoMedioSchema,
  MedioNuevoSchema,
  TerminalNuevoSchema,
  TipoDatosSchema,
  MedioDePagoSchema,
  MediosDePagoSchema,
  DatosPagoMovilSchema,
  DatosZelleSchema,
  MedioCommandSchema,
  type MedioDePagoDto,
  type MediosDePagoDto,
  type DatosPagoMovilDto,
  type DatosZelleDto,
  type MedioCommand,
  type MedioNuevoDto,
} from "./medios.ts";

export {
  TaxCodeSchema,
  TaxCodeDelCatalogoSchema,
  type TaxCodeDelCatalogo,
  TratoProgramableSchema,
  ImpuestoSchema,
  BasisPointsSchema,
  VigenciaImpuestoSchema,
  ImpuestosSchema,
  ProgramarImpuestoCommandSchema,
  type TaxCode,
  type TratoProgramable,
  type Impuesto,
  type VigenciaImpuestoDto,
  type ImpuestosDto,
  type ProgramarImpuestoCommand,
} from "./impuestos.ts";

export {
  NombreProductoSchema,
  CategoriaProductoSchema,
  PrecioMinorSchema,
  TramoPrecioSchema,
  ProductoSchema,
  CatalogoSchema,
  ProductoNuevoSchema,
  ProductoCommandSchema,
  type TramoPrecioDto,
  type ProductoDto,
  type CatalogoDto,
  type ProductoNuevoDto,
  type ProductoCommand,
  FijarMinimoCommandSchema,
  type FijarMinimoCommand,
  TipoProductoSchema,
  CodigoBarrasSchema,
  PresentacionSchema,
  type TipoProducto,
  CategoriaSchema,
  type CategoriaDto,
  MinimoSchema,
  MAX_ALTA_EN_LOTE,
  AltaEnLoteCommandSchema,
  type AltaEnLoteCommand,
} from "./productos.ts";

export { CategoriaCommandSchema, type CategoriaCommand } from "./categorias.ts";

export {
  TipoEntradaSchema,
  CostoMinorSchema,
  CostoPorSchema,
  type CostoPor,
  LineaEntradaSchema,
  ProductoDeEntradaSchema,
  type ProductoDeEntradaDto,
  RegistrarEntradaCommandSchema,
  MAX_LINEAS_ENTRADA,
  EntradaSchema,
  EntradasSchema,
  type TipoEntrada,
  type LineaEntradaDto,
  type RegistrarEntradaCommand,
  type EntradaDto,
  type EntradasDto,
} from "./entradas.ts";

export {
  MotivoSalidaSchema,
  RegistrarSalidaCommandSchema,
  RegistrarConteoCommandSchema,
  AjusteInventarioSchema,
  AjustesInventarioSchema,
  type MotivoSalida,
  type RegistrarSalidaCommand,
  type RegistrarConteoCommand,
  type AjusteInventarioDto,
  type AjustesInventarioDto,
} from "./salidas.ts";

export {
  AnchoPapelSchema,
  IpLocalSchema,
  DatosImpresoraSchema,
  EstadoTrabajoSchema,
  TipoTrabajoSchema,
  ImpresoraSchema,
  AgenteSchema,
  ImpresorasDelLocalSchema,
  ImpresoraCommandSchema,
  ImpresorasAplicadasSchema,
  TrabajoDeImpresionSchema,
  TrabajosDeImpresionSchema,
  ImprimirCorteCommandSchema,
  ImprimirPruebaCommandSchema,
  ReintentarTrabajoCommandSchema,
  DescartarTrabajosCommandSchema,
  TrabajosDescartadosSchema,
  FiltroHistorialSchema,
  POR_PAGINA_HISTORIAL,
  HistorialQuerySchema,
  ConteosHistorialSchema,
  HistorialDeImpresionSchema,
  VincularAgenteSchema,
  AgenteVinculadoSchema,
  TrabajoParaElAgenteSchema,
  ResultadoDelAgenteSchema,
  type AnchoPapel,
  type DatosImpresoraDto,
  type EstadoTrabajo,
  type TipoTrabajo,
  type ImpresoraDto,
  type AgenteDto,
  type ImpresorasDelLocalDto,
  type ImpresoraCommand,
  type ImpresorasAplicadasDto,
  type TrabajoDeImpresionDto,
  type TrabajosDeImpresionDto,
  type AgenteVinculadoDto,
  type TrabajoParaElAgenteDto,
  type ResultadoDelAgenteDto,
  type DescartarTrabajosCommand,
  type TrabajosDescartadosDto,
  type FiltroHistorial,
  type HistorialQuery,
  type HistorialDeImpresionDto,
} from "./impresoras.ts";

export {
  EstadoTurnoSchema,
  FondoInicialSchema,
  TurnoSchema,
  TurnosSchema,
  AbrirTurnoCommandSchema,
  TurnoCommandSchema,
  type EstadoTurno,
  type FondoInicialDto,
  type TurnoDto,
  type TurnosDto,
  type AbrirTurnoCommand,
  type TurnoCommand,
} from "./turno.ts";

export {
  SettlementLineSchema,
  CheckoutPreviewSchema,
  SettlementDispositionSchema,
  CheckoutCommandSchema,
  RecogidaSchema,
  type RecogidaDto,
  CheckoutResultSchema,
  type SettlementLineDto,
  type CheckoutPreviewDto,
  type SettlementDisposition,
  type CheckoutCommand,
  type CheckoutResult,
} from "./checkout.ts";

export {
  RoleSchema,
  PermissionSchema,
  PermissionExceptionSchema,
  RoleAdjustmentSchema,
  BranchAccessSchema,
  RoleAdjustmentCommandSchema,
  UserChangeSchema,
  UserSummarySchema,
  UsersDirectorySchema,
  PermissionExceptionCommandSchema,
  UserCommandSchema,
  DeviceStatusSchema,
  DeviceSchema,
  CodigoEmparejamientoSchema,
  DevicesDirectorySchema,
  DispositivosQuerySchema,
  FiltroDispositivosSchema,
  PaginaDeDispositivosSchema,
  type DispositivosQuery,
  type FiltroDispositivos,
  type PaginaDeDispositivosDto,
  DeviceCommandSchema,
  SesionEnCursoSchema,
  type RoleDto,
  type PermissionDto,
  type PermissionExceptionDto,
  type RoleAdjustmentDto,
  type BranchAccessDto,
  type RoleAdjustmentCommand,
  type UserChangeDto,
  type UserSummaryDto,
  type UsersDirectoryDto,
  type PermissionExceptionCommand,
  type UserCommand,
  type DeviceStatusDto,
  type DeviceDto,
  type DevicesDirectoryDto,
  type DeviceCommand,
  type SesionEnCursoDto,
} from "./identity.ts";

export {
  TipoDeEnlaceSchema,
  EnlaceDeAltaCommandSchema,
  EnlaceDeAltaSchema,
  LlaveDeAccesoSchema,
  CredencialesDePersonaSchema,
  EnlaceAbiertoSchema,
  PrepararAltaSchema,
  CompletarAltaSchema,
  PrepararInstalacionSchema,
  CompletarInstalacionSchema,
  PuntoDePuestaAPuntoSchema,
  PuntoDePuestaAPuntoIdSchema,
  PosponerPuntoCommandSchema,
  type PuntoDePuestaAPuntoId,
  type PosponerPuntoCommand,
  PuestaAPuntoSchema,
  EquipoDeConfianzaSchema,
  CodigoDeAppSchema,
  AppNuevaSchema,
  ConfirmarAppSchema,
  RetirarAppSchema,
  RetirarConfianzaSchema,
  type EquipoDeConfianzaDto,
  type AppNuevaDto,
  type TipoDeEnlace,
  type EnlaceDeAltaCommand,
  type EnlaceDeAltaDto,
  type LlaveDeAccesoDto,
  type CredencialesDePersonaDto,
  type EnlaceAbiertoDto,
  type PrepararAlta,
  type CompletarAlta,
  type PrepararInstalacion,
  type CompletarInstalacion,
  type PuntoDePuestaAPuntoDto,
  type PuestaAPuntoDto,
} from "./credenciales.ts";

export {
  MotivoCortesiaSchema,
  CortesiaSchema,
  MotivoAnulacionPedidoSchema,
  AnulacionPedidoSchema,
  PaymentModeSchema,
  AccountStatusSchema,
  AccountKindSchema,
  AccountLineSchema,
  DivisionCuentaSchema,
  FamilyAccountSchema,
  type PaymentMode,
  type AccountStatus,
  type AccountKind,
  type AccountLineDto,
  type DivisionCuentaDto,
  type FamilyAccountDto,
  type MotivoCortesia,
  type CortesiaDto,
  type MotivoAnulacionPedido,
  type AnulacionPedidoDto,
} from "./account.ts";

export {
  CuentasDelLocalSchema,
  GuardarCuentaCommandSchema,
  PagoDelCobroSchema,
  CobrarCuentaCommandSchema,
  CuentaYLibroSchema,
  AnularCobroCommandSchema,
  CortesiaCommandSchema,
  AnularPedidoCommandSchema,
  LiberarMesaCommandSchema,
  type CortesiaCommand,
  type AnularPedidoCommand,
  type LiberarMesaCommand,
  type CuentasDelLocalDto,
  type GuardarCuentaCommand,
  type PagoDelCobroDto,
  type CobrarCuentaCommand,
  type CuentaYLibroDto,
  type AnularCobroCommand,
} from "./cuentas.ts";

export {
  TipoReglaDescuentoSchema,
  OrigenDescuentoSchema,
  ValorDescuentoSchema,
  AlcanceDescuentoSchema,
  MotivoDescuentoSchema,
  ReglaDescuentoSchema,
  CrearReglaDescuentoCommandSchema,
  RetirarReglaDescuentoCommandSchema,
  MarcarVipCommandSchema,
  DescuentosDelLocalSchema,
  DescuentoAplicadoSchema,
  AplicarDescuentoCommandSchema,
  RequiereDescuentoSchema,
  DescuentosDeCuentaSchema,
  DescuentoDeVentaSchema,
  type TipoReglaDescuento,
  type OrigenDescuento,
  type ValorDescuentoDto,
  type AlcanceDescuentoDto,
  type MotivoDescuento,
  type ReglaDescuentoDto,
  type CrearReglaDescuentoCommand,
  type RetirarReglaDescuentoCommand,
  type MarcarVipCommand,
  type DescuentosDelLocalDto,
  type DescuentoAplicadoDto,
  type AplicarDescuentoCommand,
  type RequiereDescuento,
  type DescuentosDeCuentaDto,
  type DescuentoDeVentaDto,
} from "./descuentos.ts";

export {
  OperationEventSchema,
  type OperationEventDto,
  type OperationEventType,
} from "./eventos.ts";

export {
  CambioSchema,
  EventoDelNavegadorSchema,
  TemaSchema,
  TicketTiempoRealSchema,
  TIPOS_DEL_NAVEGADOR,
  type CambioDto,
  type Tema,
  type TicketTiempoRealDto,
} from "./tiempo-real.ts";

export {
  DiningTableSchema,
  FloorPlanSchema,
  PlanoPublicadoSchema,
  PublicarPlanoCommandSchema,
  AbrirCuentaDelSalonCommandSchema,
  CUENTAS_POR_MESA,
  type AbrirCuentaDelSalonCommand,
  EnviarPedidoCommandSchema,
  EstadoDeComandaSchema,
  LineaPedidaSchema,
  PedidoEnviadoSchema,
  PedidoSchema,
  PedidosDelLocalSchema,
  ReimprimirComandaCommandSchema,
  ServirPedidoCommandSchema,
  VincularPulserasCommandSchema,
  VincularPulserasResultSchema,
  type EnviarPedidoCommand,
  type EstadoDeComandaDto,
  type LineaPedidaDto,
  type PedidoDto,
  type PedidoEnviadoDto,
  type PedidosDelLocalDto,
  type VincularPulserasCommand,
  type VincularPulserasResultDto,
  type DiningTableDto,
  type FloorPlanDto,
  type PlanoPublicadoDto,
  type PublicarPlanoCommand,
  ElementoFijoSchema,
  FormaMesaSchema,
  PlanoLocalSchema,
  type ElementoFijoDto,
  type FormaMesa,
  type PlanoLocalDto,
} from "./restaurante.ts";

export {
  DatosDePagoSchema,
  claveDeReferencia,
  enmascararDatos,
  PosTerminalSchema,
  RedUsdtSchema,
  TelefonoVeSchema,
  DocumentoVeSchema,
  type DatosDePagoDto,
  type TipoDeDatosDePago,
  type PosTerminalDto,
  type RedUsdt,
} from "./pagos.ts";

export {
  ClienteFacturaSchema,
  CONSUMIDOR_FINAL,
  enmascararDocumento,
  type ClienteFacturaDto,
} from "./documento.ts";

export {
  AnulacionSchema,
  ClienteDeLaVentaSchema,
  DestinoSobraSchema,
  DevolucionSchema,
  ImpresionSchema,
  ImprimirVentaCommandSchema,
  MotivoAnulacionSchema,
  PagoDeVentaSchema,
  ReciboSchema,
  VentaCerradaSchema,
  VentasDelTurnoSchema,
  type AnulacionDto,
  type ClienteDeLaVentaDto,
  type DestinoSobra,
  type DevolucionDto,
  type ImpresionDto,
  type ImprimirVentaCommand,
  type MotivoAnulacion,
  type PagoDeVentaDto,
  type ReciboDto,
  type VentaCerradaDto,
  type VentasDelTurnoDto,
} from "./ventas.ts";

export {
  TipoAsientoSchema,
  AsientoNuevoSchema,
  AsentarPagosCommandSchema,
  RevertirPagoCommandSchema,
  AsientoSchema,
  LibroDocumentoSchema,
  type TipoAsiento,
  type AsientoNuevoDto,
  type AsentarPagosCommand,
  type RevertirPagoCommand,
  type AsientoDto,
  type LibroDocumentoDto,
} from "./libro.ts";

export {
  FeriadoSchema,
  FeriadosSchema,
  RegistrarFeriadoCommandSchema,
  RetirarFeriadoCommandSchema,
  type FeriadoDto,
  type FeriadosDto,
  type RegistrarFeriadoCommand,
  type RetirarFeriadoCommand,
} from "./feriados.ts";

export {
  HoraDelDiaSchema,
  DiaSemanaSchema,
  HorarioDelDiaSchema,
  ServicioSchema,
  AjustesSucursalSchema,
  AjustesPublicadosSchema,
  FormatoPulserasSchema,
  type FormatoPulserasDto,
  PublicarAjustesCommandSchema,
  MAX_RESIDUO_MINOR,
  MAX_UMBRAL_ARQUEO_MINOR,
  type AjustesPublicadosDto,
  type PublicarAjustesCommand,
  type HoraDelDia,
  type DiaSemana,
  type HorarioDelDiaDto,
  type ServicioDto,
  type AjustesSucursalDto,
} from "./sucursal.ts";

export {
  MotivoDeRechazoSchema,
  ProblemaSchema,
  problemasDe,
  type MotivoDeRechazo,
  type Problema,
  type Rechazo,
  type Resultado,
} from "./resultado.ts";

export {
  ArqueoCommandSchema,
  ArqueoSchema,
  ComprobacionAperturaSchema,
  ConteoMonedaSchema,
  CorteSchema,
  CorteXCommandSchema,
  CorteZCommandSchema,
  ExcepcionSchema,
  FirmaZSchema,
  GavetaSchema,
  IncobrableCommandSchema,
  MotivoIncobrableSchema,
  MovimientoPorMedioSchema,
  PendientesDelCierreSchema,
  ResumenDelDiaSchema,
  TipoDeCierreSchema,
  type ArqueoCommand,
  type ArqueoDto,
  type ComprobacionAperturaDto,
  type ConteoMonedaDto,
  type CorteDto,
  type CorteXCommand,
  type CorteZCommand,
  type ExcepcionDto,
  type FirmaZ,
  type GavetaDto,
  type IncobrableCommand,
  type MotivoIncobrable,
  type MovimientoPorMedioDto,
  type PendientesDelCierreDto,
  type ResumenDelDiaDto,
  type TipoDeCierre,
} from "./cortes.ts";

export {
  ANTICIPO_POR_DEFECTO_BPS,
  AgendaEventosQuerySchema,
  AgendaEventosSchema,
  CancelarReservaCommandSchema,
  CatalogoEventosPublicadoSchema,
  CatalogoEventosSchema,
  EmpezarEventoCommandSchema,
  EntradaEventoCommandSchema,
  EstadoReservaSchema,
  IncluidoEnPaqueteSchema,
  MinutoDelDiaSchema,
  PaqueteEventoSchema,
  PublicarCatalogoEventosCommandSchema,
  ReservaEventoSchema,
  ReservarEventoCommandSchema,
  type AgendaEventosDto,
  type AgendaEventosQuery,
  type CancelarReservaCommand,
  type CatalogoEventosDto,
  type CatalogoEventosPublicadoDto,
  type EmpezarEventoCommand,
  type EntradaEventoCommand,
  type EstadoReserva,
  type IncluidoEnPaqueteDto,
  type PaqueteEventoDto,
  type PublicarCatalogoEventosCommand,
  type ReservaEventoDto,
  type ReservarEventoCommand,
} from "./reservas.ts";

export {
  AbrirCargaCommandSchema,
  CargaDePapelSchema,
  CargaPendienteSchema,
  CargasDePapelSchema,
  DesdePapelSchema,
  EstadoDeCargaSchema,
  MarcaDePapelSchema,
  RegistroDePapelSchema,
  RevisarCargaCommandSchema,
  TerminarCargaCommandSchema,
  TipoDeRegistroSchema,
  type AbrirCargaCommand,
  type CargaDePapelDto,
  type CargaPendienteDto,
  type CargasDePapelDto,
  type DesdePapel,
  type EstadoDeCargaDto,
  type MarcaDePapelDto,
  type RegistroDePapelDto,
  type RevisarCargaCommand,
  type TerminarCargaCommand,
  type TipoDeRegistro,
} from "./papel.ts";

export {
  SemillaSchema,
  ProductoDeSemillaSchema,
  PaqueteDeSemillaSchema,
  ParteDeSemillaSchema,
  InformeDeSemillaSchema,
  CargarSemillaCommandSchema,
  type SemillaDto,
  type ProductoDeSemillaDto,
  type ParteDeSemilla,
  type InformeDeSemillaDto,
  type CargarSemillaCommand,
} from "./semilla.ts";

export {
  NumeroDeVersionSchema,
  VersionDisponibleSchema,
  ModoDeActualizacionSchema,
  EstadoDeActualizacionSchema,
  ActualizacionSchema,
  EstadoDelSistemaSchema,
  PedirActualizacionCommandSchema,
  CancelarActualizacionCommandSchema,
  type VersionDisponibleDto,
  type ModoDeActualizacion,
  type EstadoDeActualizacion,
  type ActualizacionDto,
  type EstadoDelSistemaDto,
  type PedirActualizacionCommand,
} from "./sistema.ts";
export {
  ArchivoDeRespaldoSchema,
  HuellaSha256Schema,
  CopiaDeRespaldoSchema,
  NivelDeRespaldosSchema,
  EstadoDeRespaldosSchema,
  IndiceDeRespaldosSchema,
  AcuseDeRespaldoCommandSchema,
  PcDeRespaldosSchema,
  PrepararPcDeRespaldosCommandSchema,
  PcPreparadaSchema,
  RetirarPcDeRespaldosCommandSchema,
  type PcDeRespaldosDto,
  type PrepararPcDeRespaldosCommand,
  type PcPreparadaDto,
  type CopiaDeRespaldoDto,
  type NivelDeRespaldos,
  type EstadoDeRespaldosDto,
  type IndiceDeRespaldosDto,
  type AcuseDeRespaldoCommand,
} from "./respaldos.ts";

export {
  RecorridoIdSchema,
  RecorridoVistoCommandSchema,
  RecorridosVistosSchema,
  type RecorridoVistoCommand,
  type RecorridosVistosDto,
} from "./ayuda.ts";

export {
  CAPTURA_MAX_BYTES,
  ERRORES_ADJUNTOS,
  CapturaSchema,
  EstadoDeReporteCommandSchema,
  EstadoReporteSchema,
  PasoDeReporteSchema,
  ReporteEnviadoSchema,
  ReporteSchema,
  ReportarCommandSchema,
  ReportesSchema,
  type CapturaDto,
  type EstadoDeReporteCommand,
  type EstadoReporte,
  type ReporteDto,
  type ReporteEnviadoDto,
  type ReportarCommand,
  type ReportesDto,
} from "./soporte.ts";
