/**
 * @l2/contracts — API pública.
 *
 * §9.3: lo que no se exporta aquí no es importable desde fuera. Un contrato
 * que no está en esta lista todavía no es un contrato, es un borrador.
 */

export {
  IdSchema,
  TimestampSchema,
  FechaSchema,
  CurrencySchema,
  MoneySchema,
  IdempotencyKeySchema,
  ApiErrorSchema,
  type Id,
  type Timestamp,
  type Fecha,
  type Currency,
  type MoneyDto,
  type IdempotencyKey,
  type ApiError,
} from "./primitives.ts";

export {
  WristbandCodeSchema,
  GuardianSchema,
  KidSchema,
  DurationSchema,
  SessionModeSchema,
  PricePackageSchema,
  ParkPolicySchema,
  TarifarioSchema,
  SessionStatusSchema,
  ParkSessionSchema,
  ParkTermsSchema,
  EstanciaSchema,
  BuscarRepresentanteSchema,
  RepresentanteEncontradoSchema,
  RecargaCommandSchema,
  RecargaResultSchema,
  CierreHuerfanaCommandSchema,
  type RecargaCommand,
  type RecargaResult,
  type CierreHuerfanaCommand,
  MonitorSnapshotSchema,
  CheckInCommandSchema,
  CheckInResultSchema,
  RepresentanteSchema,
  DirectorioRepresentantesSchema,
  RepresentanteCommandSchema,
  NombrarEstanciaCommandSchema,
  type WristbandCode,
  type GuardianDto,
  type KidDto,
  type DurationDto,
  type SessionMode,
  type PricePackageDto,
  type ParkPolicyDto,
  type TarifarioDto,
  TarifarioPublicadoSchema,
  type TarifarioPublicadoDto,
  type SessionStatus,
  type ParkSessionDto,
  type ParkTermsDto,
  type EstanciaDto,
  type RepresentanteEncontradoDto,
  type MonitorSnapshotDto,
  type CheckInCommand,
  type RepresentanteDto,
  type DirectorioRepresentantesDto,
  type RepresentanteCommand,
  type NombrarEstanciaCommand,
  type CheckInResult,
} from "./park.ts";

export {
  RatePairSchema,
  RateSourceSchema,
  RateValueSchema,
  HeldReasonSchema,
  AlertaTasaSchema,
  ExchangeRateSchema,
  HistorialTasasSchema,
  CapturarTasaCommandSchema,
  ConfirmarTasaCommandSchema,
  SincronizacionTasaSchema,
  type RatePair,
  type RateSource,
  type HeldReason,
  type AlertaTasaDto,
  type ExchangeRateDto,
  type HistorialTasasDto,
  type CapturarTasaCommand,
  type ConfirmarTasaCommand,
  type SincronizacionTasaDto,
} from "./tasas.ts";

export {
  CodigoMedioSchema,
  MedioNuevoSchema,
  TerminalNuevoSchema,
  TipoDatosSchema,
  MedioDePagoSchema,
  MediosDePagoSchema,
  DatosPagoMovilSchema,
  DatosZelleSchema,
  MedioCommandSchema,
  type MedioDePagoDto,
  type MediosDePagoDto,
  type DatosPagoMovilDto,
  type DatosZelleDto,
  type MedioCommand,
  type MedioNuevoDto,
} from "./medios.ts";

export {
  TaxCodeSchema,
  TaxCodeDelCatalogoSchema,
  type TaxCodeDelCatalogo,
  TratoProgramableSchema,
  ImpuestoSchema,
  BasisPointsSchema,
  VigenciaImpuestoSchema,
  ImpuestosSchema,
  ProgramarImpuestoCommandSchema,
  type TaxCode,
  type TratoProgramable,
  type Impuesto,
  type VigenciaImpuestoDto,
  type ImpuestosDto,
  type ProgramarImpuestoCommand,
} from "./impuestos.ts";

export {
  NombreProductoSchema,
  CategoriaProductoSchema,
  PrecioMinorSchema,
  TramoPrecioSchema,
  ProductoSchema,
  CatalogoSchema,
  ProductoNuevoSchema,
  ProductoCommandSchema,
  type TramoPrecioDto,
  type ProductoDto,
  type CatalogoDto,
  type ProductoNuevoDto,
  type ProductoCommand,
} from "./productos.ts";

export {
  OficioImpresoraSchema,
  AnchoPapelSchema,
  IpLocalSchema,
  ImpresoraSchema,
  ImpresorasSchema,
  ImpresoraCommandSchema,
  type OficioImpresora,
  type AnchoPapel,
  type ImpresoraDto,
  type ImpresorasDto,
  type ImpresoraCommand,
} from "./impresoras.ts";

export {
  EstadoTurnoSchema,
  FondoInicialSchema,
  TurnoSchema,
  TurnosSchema,
  AbrirTurnoCommandSchema,
  TurnoCommandSchema,
  type EstadoTurno,
  type FondoInicialDto,
  type TurnoDto,
  type TurnosDto,
  type AbrirTurnoCommand,
  type TurnoCommand,
} from "./turno.ts";

export {
  SettlementLineSchema,
  CheckoutPreviewSchema,
  SettlementDispositionSchema,
  CheckoutCommandSchema,
  RecogidaSchema,
  type RecogidaDto,
  CheckoutResultSchema,
  type SettlementLineDto,
  type CheckoutPreviewDto,
  type SettlementDisposition,
  type CheckoutCommand,
  type CheckoutResult,
} from "./checkout.ts";

export {
  RoleSchema,
  PermissionSchema,
  PermissionExceptionSchema,
  RoleAdjustmentSchema,
  BranchAccessSchema,
  RoleAdjustmentCommandSchema,
  UserChangeSchema,
  UserSummarySchema,
  UsersDirectorySchema,
  PermissionExceptionCommandSchema,
  UserCommandSchema,
  DeviceStatusSchema,
  DeviceSchema,
  CodigoEmparejamientoSchema,
  DevicesDirectorySchema,
  DeviceCommandSchema,
  SesionEnCursoSchema,
  type RoleDto,
  type PermissionDto,
  type PermissionExceptionDto,
  type RoleAdjustmentDto,
  type BranchAccessDto,
  type RoleAdjustmentCommand,
  type UserChangeDto,
  type UserSummaryDto,
  type UsersDirectoryDto,
  type PermissionExceptionCommand,
  type UserCommand,
  type DeviceStatusDto,
  type DeviceDto,
  type DevicesDirectoryDto,
  type DeviceCommand,
  type SesionEnCursoDto,
} from "./identity.ts";

export {
  MotivoCortesiaSchema,
  CortesiaSchema,
  PaymentModeSchema,
  AccountStatusSchema,
  AccountKindSchema,
  AccountLineSchema,
  DivisionCuentaSchema,
  FamilyAccountSchema,
  type PaymentMode,
  type AccountStatus,
  type AccountKind,
  type AccountLineDto,
  type DivisionCuentaDto,
  type FamilyAccountDto,
  type MotivoCortesia,
  type CortesiaDto,
} from "./account.ts";

export {
  CuentasDelLocalSchema,
  GuardarCuentaCommandSchema,
  PagoDelCobroSchema,
  CobrarCuentaCommandSchema,
  CuentaYLibroSchema,
  AnularCobroCommandSchema,
  CortesiaCommandSchema,
  type CortesiaCommand,
  type CuentasDelLocalDto,
  type GuardarCuentaCommand,
  type PagoDelCobroDto,
  type CobrarCuentaCommand,
  type CuentaYLibroDto,
  type AnularCobroCommand,
} from "./cuentas.ts";

export {
  OperationEventSchema,
  OrderItemSchema,
  type OperationEventDto,
  type OperationEventType,
  type OrderItemDto,
} from "./eventos.ts";

export {
  CambioSchema,
  EventoDelNavegadorSchema,
  TemaSchema,
  TicketTiempoRealSchema,
  TIPOS_DEL_NAVEGADOR,
  type CambioDto,
  type Tema,
  type TicketTiempoRealDto,
} from "./tiempo-real.ts";

export {
  DiningTableSchema,
  FloorPlanSchema,
  MenuItemSchema,
  MenuSchema,
  type DiningTableDto,
  type FloorPlanDto,
  type MenuItemDto,
  type MenuDto,
  ElementoFijoSchema,
  FormaMesaSchema,
  PlanoLocalSchema,
  type ElementoFijoDto,
  type FormaMesa,
  type PlanoLocalDto,
} from "./restaurante.ts";

export {
  DatosDePagoSchema,
  claveDeReferencia,
  enmascararDatos,
  PosTerminalSchema,
  RedUsdtSchema,
  TelefonoVeSchema,
  DocumentoVeSchema,
  type DatosDePagoDto,
  type TipoDeDatosDePago,
  type PosTerminalDto,
  type RedUsdt,
} from "./pagos.ts";

export {
  ClienteFacturaSchema,
  CONSUMIDOR_FINAL,
  enmascararDocumento,
  type ClienteFacturaDto,
} from "./documento.ts";

export {
  AnulacionSchema,
  ClienteDeLaVentaSchema,
  DestinoSobraSchema,
  DevolucionSchema,
  ImpresionSchema,
  ImprimirVentaCommandSchema,
  MotivoAnulacionSchema,
  PagoDeVentaSchema,
  ReciboSchema,
  VentaCerradaSchema,
  VentasDelTurnoSchema,
  type AnulacionDto,
  type ClienteDeLaVentaDto,
  type DestinoSobra,
  type DevolucionDto,
  type ImpresionDto,
  type ImprimirVentaCommand,
  type MotivoAnulacion,
  type PagoDeVentaDto,
  type ReciboDto,
  type VentaCerradaDto,
  type VentasDelTurnoDto,
} from "./ventas.ts";

export {
  TipoAsientoSchema,
  AsientoNuevoSchema,
  AsentarPagosCommandSchema,
  RevertirPagoCommandSchema,
  AsientoSchema,
  LibroDocumentoSchema,
  type TipoAsiento,
  type AsientoNuevoDto,
  type AsentarPagosCommand,
  type RevertirPagoCommand,
  type AsientoDto,
  type LibroDocumentoDto,
} from "./libro.ts";

export {
  FeriadoSchema,
  FeriadosSchema,
  RegistrarFeriadoCommandSchema,
  RetirarFeriadoCommandSchema,
  type FeriadoDto,
  type FeriadosDto,
  type RegistrarFeriadoCommand,
  type RetirarFeriadoCommand,
} from "./feriados.ts";

export {
  HoraDelDiaSchema,
  DiaSemanaSchema,
  HorarioDelDiaSchema,
  ServicioSchema,
  AjustesSucursalSchema,
  type HoraDelDia,
  type DiaSemana,
  type HorarioDelDiaDto,
  type ServicioDto,
  type AjustesSucursalDto,
} from "./sucursal.ts";

export {
  MotivoDeRechazoSchema,
  ProblemaSchema,
  problemasDe,
  type MotivoDeRechazo,
  type Problema,
  type Rechazo,
  type Resultado,
} from "./resultado.ts";

export {
  ArqueoCommandSchema,
  ArqueoSchema,
  ComprobacionAperturaSchema,
  ConteoMonedaSchema,
  CorteSchema,
  CorteXCommandSchema,
  CorteZCommandSchema,
  ExcepcionSchema,
  FirmaZSchema,
  GavetaSchema,
  IncobrableCommandSchema,
  MotivoIncobrableSchema,
  MovimientoPorMedioSchema,
  PendientesDelCierreSchema,
  ResumenDelDiaSchema,
  TipoDeCierreSchema,
  type ArqueoCommand,
  type ArqueoDto,
  type ComprobacionAperturaDto,
  type ConteoMonedaDto,
  type CorteDto,
  type CorteXCommand,
  type CorteZCommand,
  type ExcepcionDto,
  type FirmaZ,
  type GavetaDto,
  type IncobrableCommand,
  type MotivoIncobrable,
  type MovimientoPorMedioDto,
  type PendientesDelCierreDto,
  type ResumenDelDiaDto,
  type TipoDeCierre,
} from "./cortes.ts";
